### ISSUE TITLE
项目部署问题

### ISSUE THREAD

**Issue by wenzhaoxian** [yangsoon/funny-bot#2]
raise BotApiError(err_msg, response=response)
![image](https://user-images.githubusercontent.com/48466044/71497671-3a809e80-2894-11ea-864c-fdc3dd0e442d.png)

**Comment by yangsoon** [comment]
不好意思，请问你在bot文件夹下面创建 token.json文件了吗

**Comment by yangsoon** [comment]
我刚刚重新跑了一下，发现当前构建docker的时候，没有考虑好，现在依赖的docker版本也变了。
我新建了一个分支 test，这个分支不支持docker-compose，直接在本机启动就行。

关于启动telegram bot，需要在bot文件夹下面新建一个token.json文件，这个文件需要你填一个token字段，这个token代表你机器人的唯一id，你需要在tg里面添加 botfather来创建和申请token。具体的信息请你参考这个文章 [https://github.com/yangsoon/yangsoon.github.io/issues/21#new_comment_field](https://github.com/yangsoon/yangsoon.github.io/issues/21#new_comment_field) 里面的 BotFather部分。

其次如果你本机访问外网需要翻墙的话，在token.json中需要填写proxy字段这样就可以使用代理，这个字段值需要填写你自己的代理服务。

### 安装流程：
前提是在test分支下
1.  修改bot文件夹下面的token.json 填写相应的值
2.  执行 `pip3 install -r requirements.txt`
3.  在bot下面执行 python3 main.py

**Comment by yangsoon** [comment]
这个项目是2年前写的了，当时随便写写的，没想到有人会用，实在不好意思。
